
modLoader = "javafml"
loaderVersion = "[50,)"
license = "MIT"
issueTrackerURL = ""
modProperties = "ModProperties"

[[mods]]
modId = "armorforu"
version = "6.6.6"
displayName = "Armor ForU Mod"
description = "A mod that adds different armors to the game."
authors = "bub"
displayURL = ""

[[dependencies.armorforu]]
modId = "forge"
mandatory = true
versionRange = "[50,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armorforu]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

